export const LOADING = 'LOADING';
export const LOADING2 = 'LOADING2';

// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const CONFIRMATION_SUCCESS = 'CONFIRMATION_SUCCESS';
export const CONFIRMATION_FAIL = 'CONFIRMATION_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const SENDMAIL_SUCCESS = 'SENDMAIL_SUCCESS';
export const SENDMAIL_FAIL = 'SENDMAIL_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

// Post
export const GET_MYPOSTS = 'GET_MYPOSTS';
export const GET_MYPOSTS_ERROR = 'GET_MYPOSTS_ERROR';
export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';
export const UPDATE_LIKES = 'UPDATE_LIKES';
export const UPDATE_COMMENTS = 'UPDATE_COMMENTS';
export const ADD_POST = 'ADD_POST';
export const ADD_POST_ERROR = 'ADD_POST_ERROR';
export const DELETE_POST = 'DELETE_POST';
export const GET_POST = 'GET_POST';
export const UPDATE_LIKES_SINGLE = 'UPDATE_LIKES_SINGLE';
export const UPDATE_COMMENTS_SINGLE = 'UPDATE_COMMENTS_SINGLE';

// Notification
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';
